import type { Vehicle } from "./types";

// Starting-estimate database of popular family vehicles.
//
// IMPORTANT: linear cargo dimensions are rarely published the way volumes are,
// so these are reasonable estimates derived from published cargo volumes and
// typical packaging. They are intended as an editable starting point — the UI
// lets families verify and adjust every number against the manufacturer's spec
// sheet (or against a tape measure in the dealership lot).

export const VEHICLES: Vehicle[] = [
  {
    id: "sienna",
    make: "Toyota",
    model: "Sienna",
    years: "2021–2026",
    category: "Minivan",
    rows: 3,
    cargoWidth: 48,
    cargoHeight: 34,
    lengthBehindLastRow: 21,
    lengthThirdFolded: 42,
    lengthAllRearFolded: 84,
    secondRowWidth: 62,
    secondRowSeats: 2,
    secondRowLegroomMax: 40,
    secondRowLegroomMin: 28,
    cargoCuFtBehindLast: 33,
    cargoCuFtMax: 101,
    estimated: true,
  },
  {
    id: "odyssey",
    make: "Honda",
    model: "Odyssey",
    years: "2018–2025",
    category: "Minivan",
    rows: 3,
    cargoWidth: 49,
    cargoHeight: 34,
    lengthBehindLastRow: 20,
    lengthThirdFolded: 40,
    lengthAllRearFolded: 82,
    secondRowWidth: 63,
    secondRowSeats: 3,
    secondRowLegroomMax: 40,
    secondRowLegroomMin: 28,
    cargoCuFtBehindLast: 32,
    cargoCuFtMax: 144,
    estimated: true,
  },
  {
    id: "pacifica",
    make: "Chrysler",
    model: "Pacifica",
    years: "2017–2026",
    category: "Minivan",
    rows: 3,
    cargoWidth: 49,
    cargoHeight: 36,
    lengthBehindLastRow: 20,
    lengthThirdFolded: 45,
    lengthAllRearFolded: 87,
    secondRowWidth: 64,
    secondRowSeats: 2,
    secondRowLegroomMax: 41,
    secondRowLegroomMin: 28,
    cargoCuFtBehindLast: 33,
    cargoCuFtMax: 141,
    estimated: true,
  },
  {
    id: "telluride",
    make: "Kia",
    model: "Telluride",
    years: "2020–2026",
    category: "3-Row SUV",
    rows: 3,
    cargoWidth: 45,
    cargoHeight: 34,
    lengthBehindLastRow: 21,
    lengthThirdFolded: 38,
    lengthAllRearFolded: 74,
    secondRowWidth: 60,
    secondRowSeats: 3,
    secondRowLegroomMax: 42,
    secondRowLegroomMin: 30,
    cargoCuFtBehindLast: 21,
    cargoCuFtMax: 87,
    estimated: true,
  },
  {
    id: "highlander",
    make: "Toyota",
    model: "Highlander",
    years: "2020–2026",
    category: "3-Row SUV",
    rows: 3,
    cargoWidth: 42,
    cargoHeight: 32,
    lengthBehindLastRow: 16,
    lengthThirdFolded: 35,
    lengthAllRearFolded: 72,
    secondRowWidth: 58,
    secondRowSeats: 3,
    secondRowLegroomMax: 41,
    secondRowLegroomMin: 28,
    cargoCuFtBehindLast: 16,
    cargoCuFtMax: 84,
    estimated: true,
  },
  {
    id: "pilot",
    make: "Honda",
    model: "Pilot",
    years: "2023–2026",
    category: "3-Row SUV",
    rows: 3,
    cargoWidth: 44,
    cargoHeight: 34,
    lengthBehindLastRow: 18,
    lengthThirdFolded: 40,
    lengthAllRearFolded: 78,
    secondRowWidth: 60,
    secondRowSeats: 3,
    secondRowLegroomMax: 41,
    secondRowLegroomMin: 28,
    cargoCuFtBehindLast: 22,
    cargoCuFtMax: 87,
    estimated: true,
  },
  {
    id: "ascent",
    make: "Subaru",
    model: "Ascent",
    years: "2019–2026",
    category: "3-Row SUV",
    rows: 3,
    cargoWidth: 43,
    cargoHeight: 33,
    lengthBehindLastRow: 17,
    lengthThirdFolded: 36,
    lengthAllRearFolded: 72,
    secondRowWidth: 58,
    secondRowSeats: 3,
    secondRowLegroomMax: 39,
    secondRowLegroomMin: 27,
    cargoCuFtBehindLast: 17,
    cargoCuFtMax: 86,
    estimated: true,
  },
  {
    id: "rav4",
    make: "Toyota",
    model: "RAV4",
    years: "2019–2025",
    category: "2-Row SUV",
    rows: 2,
    cargoWidth: 41,
    cargoHeight: 32,
    lengthBehindLastRow: 36,
    lengthThirdFolded: 69,
    lengthAllRearFolded: 69,
    secondRowWidth: 54,
    secondRowSeats: 3,
    secondRowLegroomMax: 38,
    secondRowLegroomMin: 27,
    cargoCuFtBehindLast: 37,
    cargoCuFtMax: 69,
    estimated: true,
  },
  {
    id: "crv",
    make: "Honda",
    model: "CR-V",
    years: "2023–2026",
    category: "2-Row SUV",
    rows: 2,
    cargoWidth: 41,
    cargoHeight: 32,
    lengthBehindLastRow: 38,
    lengthThirdFolded: 72,
    lengthAllRearFolded: 72,
    secondRowWidth: 55,
    secondRowSeats: 3,
    secondRowLegroomMax: 41,
    secondRowLegroomMin: 28,
    cargoCuFtBehindLast: 39,
    cargoCuFtMax: 76,
    estimated: true,
  },
  {
    id: "camry",
    make: "Toyota",
    model: "Camry",
    years: "2018–2025",
    category: "Sedan",
    rows: 2,
    cargoWidth: 42,
    cargoHeight: 18,
    lengthBehindLastRow: 42,
    lengthThirdFolded: 60,
    lengthAllRearFolded: 60,
    secondRowWidth: 54,
    secondRowSeats: 3,
    secondRowLegroomMax: 38,
    secondRowLegroomMin: 28,
    cargoCuFtBehindLast: 15,
    estimated: true,
  },
];

export function findVehicle(id: string): Vehicle | undefined {
  return VEHICLES.find((v) => v.id === id);
}
